name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  # sphinxdoc/sphinx, sphinxdoc/sphinx-latexpdf
  BASEIMAGE: sphinxdoc/sphinx
  NAME: sphinx-builder

jobs:

  # build:
  #   runs-on: ubuntu-latest
  #   environment: Production
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build the Docker image
  #     run: |
  #       # docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  #       docker build \
  #         --build-arg BASE_IMAGE="$BASEIMAGE" \
  #         --build-arg VERSION="$VERSION" \
  #         --build-arg REPO_NAME="hedzr/sphinx-docker" \
  #         --build-arg APT_MIRROR="$APT_MIRROR" \
  #         -t $NAME:latest -t $NAME:$VERSION \
  #         --progress=plain \
  #         . \
  #         2>&1 | tee build-$NAME.log


  docker:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${NAME}:latest,${NAME}:${RELEASE_VERSION}
          build-args: BASE_IMAGE="$BASEIMAGE",VERSION="$RELEASE_VERSION",REPO_NAME="hedzr/sphinx-docker"



#
