name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  # sphinxdoc/sphinx, sphinxdoc/sphinx-latexpdf
  BASEIMAGE: sphinxdoc/sphinx
  NAME: sphinx-builder

jobs:

  # build:
  #   runs-on: ubuntu-latest
  #   environment: Production
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build the Docker image
  #     run: |
  #       # docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  #       docker build \
  #         --build-arg BASE_IMAGE="$BASEIMAGE" \
  #         --build-arg VERSION="$VERSION" \
  #         --build-arg REPO_NAME="hedzr/sphinx-docker" \
  #         --build-arg APT_MIRROR="$APT_MIRROR" \
  #         -t $NAME:latest -t $NAME:$VERSION \
  #         --progress=plain \
  #         . \
  #         2>&1 | tee build-$NAME.log


  docker:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "ACTOR=${GITHUB_REPOSITORY_OWNER}" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY}" >> $GITHUB_ENV
          [ "${GITHUB_REF#refs/*/}" = "master" ] && IMG_VERSION=5.3.0 || IMG_VERSION=${GITHUB_REF#refs/*/v}
          echo "IMG_VERSION=$IMG_VERSION" >> $GITHUB_ENV
          echo "IMG_NAME=${GITHUB_REPOSITORY_OWNER}/${NAME}" >> $GITHUB_ENV
          echo "$IMG_NAME, $REPO_NAME, $ACTION, $RELEASE_VERSION"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.IMG_NAME }}:latest
            ${{ env.IMG_NAME }}:${{ env.RELEASE_VERSION }}
            ghcr.io/${{ env.IMG_NAME }}:latest
            ghcr.io/${{ env.IMG_NAME }}:${{ env.RELEASE_VERSION }}
          build-args: |
            BASE_IMAGE=${{ env.BASEIMAGE }}
            VERSION=${{ env.IMG_VERSION }}
            REPO_NAME=${{ env.REPO_NAME }}



#
